FROM python:3.10

WORKDIR /app

COPY backend/ /app/
COPY entrypoint.sh /entrypoint.sh

RUN apt-get update && apt-get install -y postgresql-client \
    && pip install --upgrade pip \
    && pip install -r requirements.txt \
    && chmod +x /entrypoint.sh

RUN pip install --upgrade pip && pip install -r requirements.txt
ENTRYPOINT ["/entrypoint.sh"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
