FROM node:18

# 设置工作目录
WORKDIR /app

# 拷贝前端代码
COPY frontend/ /app/

# 安装依赖
RUN npm install --verbose

# 开发环境配置
ENV HOST 0.0.0.0
ENV PORT 8080
ENV CHOKIDAR_USEPOLLING=true

# 启动开发服务器（Vite 或 Vue CLI）
CMD ["npm", "run", "dev"]
